ballantines:
  - magellan
  - becherovka
  - xenta
  - baileys
  - tokaji
  - dmf
dmf:
  - magellan
  - becherovka
  - xenta
  - baileys
  - tokaji
  - ballantines
magellan:
  - ballantines
  - becherovka
  - xenta
  - baileys
  - tokaji
  - dmf
becherovka:
  - ballantines
  - magellan
  - xenta
  - baileys
  - tokaji
  - dmf
xenta:
  - ballantines
  - magellan
  - becherovka
  - baileys
  - tokaji
  - dmf
baileys:
  - ballantines
  - magellan
  - becherovka
  - xenta
  - tokaji
  - dmf
tokaji:
  - ballantines
  - magellan
  - becherovka
  - xenta
  - baileys
  - dmf
