ballantines:
  - magellan
  - becherovka
  - xenta
  - baileys
  - tokaji
dmf: []
magellan:
  - ballantines
  - becherovka
  - xenta
  - baileys
  - tokaji
becherovka:
  - ballantines
  - magellan
  - xenta
  - baileys
  - tokaji
xenta:
  - ballantines
  - magellan
  - becherovka
  - baileys
  - tokaji
baileys:
  - ballantines
  - magellan
  - becherovka
  - xenta
  - tokaji
tokaji:
  - ballantines
  - magellan
  - becherovka
  - xenta
  - baileys
