version: '3.8'
x-app: &x-app
  image: wt-app
  command:
    - ./wait-for
    - wt-database:5432
    - -t
    - '10'
    - --
    - go
    - run
    - github.com/xXxRisingTidexXx/wt-labs/cmd/lw4
  volumes:
    - ./go.mod:/go/src/app/go.mod
    - ./go.sum:/go/src/app/go.sum
    - ./cmd:/go/src/app/cmd
    - ./pkg:/go/src/app/pkg
    - ./internal:/go/src/app/internal
  depends_on:
    - database
x-environment: &x-environment
  WT_DSN: postgres://postgres:postgres@wt-database:5432/wt?sslmode=disable
services:
  database:
    image: postgres:13.2-alpine
    container_name: wt-database
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
  migrate:
    build:
      context: .
      dockerfile: docker/migrate.dockerfile
    image: wt-migrate
    container_name: wt-migrate
    entrypoint: ./wait-for wt-database:5432 -t 10 -- migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - database
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    image: wt-app
  app-ballantines:
    <<: *x-app
    container_name: wt-app-ballantines
    ports:
      - 9292:80
    environment:
      <<: *x-environment
      WT_NODE: ballantines
  app-dmf:
    <<: *x-app
    container_name: wt-app-dmf
    ports:
      - 9293:80
    environment:
      <<: *x-environment
      WT_NODE: dmf
  app-magellan:
    <<: *x-app
    container_name: wt-app-magellan
    ports:
      - 9294:80
    environment:
      <<: *x-environment
      WT_NODE: magellan
  app-becherovka:
    <<: *x-app
    container_name: wt-app-becherovka
    ports:
      - 9295:80
    environment:
      <<: *x-environment
      WT_NODE: becherovka
  app-xenta:
    <<: *x-app
    container_name: wt-app-xenta
    ports:
      - 9296:80
    environment:
      <<: *x-environment
      WT_NODE: xenta
  app-baileys:
    <<: *x-app
    container_name: wt-app-baileys
    ports:
      - 9297:80
    environment:
      <<: *x-environment
      WT_NODE: baileys
  app-tokaji:
    <<: *x-app
    container_name: wt-app-tokaji
    ports:
      - 9298:80
    environment:
      <<: *x-environment
      WT_NODE: tokaji
volumes:
  database:
    name: wt-database
networks:
  default:
    name: wt-default
